[package]
name = "falling-sand"
version = "0.1.0"
authors = ["Simon Voordouw <simonvoordouw@gmail.com>"]
edition = "2021"

[dependencies]
enum-map = "1.1.1"
ndarray = "0.15"
bevy = { version = "0.6", features = [ "wayland", "trace" ] }
