name: Build Windows

on:
  workflow_call:

permissions:
  contents: read

jobs:
  build-windows:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: cachix/install-nix-action@V27
        with:
          github_access_token: ${{ secrets.GITHUB_TOKEN }}
      - uses: DeterminateSystems/magic-nix-cache-action@main
      - run: nix build .#falling-sand-win64 -L
      - uses: actions/upload-artifact@v4
        with:
          name: falling-sand-win64
          path: ./result
