name: Check web build

on:
  pull_request:
    paths:
      - "Cargo.lock"
      - "Cargo.toml"
      - "flake.lock"
      - "flake.nix"

jobs:
  build-web:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: DeterminateSystems/nix-installer-action@main
      - uses: DeterminateSystems/magic-nix-cache-action@main
      - run: nix build .#falling-sand-web -L
