name: Deploy to Pages

on:
  workflow_call:

permissions:
  contents: read
  pages: write
  id-token: write

jobs:
  deploy-to-pages:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: DeterminateSystems/nix-installer-action@main
      - uses: DeterminateSystems/magic-nix-cache-action@main
      - run: nix build .#falling-sand-web -L
      - name: Setup Pages
        uses: actions/configure-pages@v5
      - name: Upload artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: './result'
      - name: Deploy to Github Pages
        uses: actions/deploy-pages@v4
