name: Test, Build & Release

on:
  push:
    branches: ["master"]

jobs:
  test:
    uses: ./.github/workflows/test.yml

  create-release:
    needs: test
    uses: ./.github/workflows/create-release.yml

  build-release:
    needs: create-release
    uses: ./.github/workflows/release.yml
